#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  echo "macOS detected"

  if [ ! command -v brew >/dev/null 2>&1]; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

	if [ command -v vim > /dev/null 2>&1]; then
		if [ ! -e $HOME/.vim/bundle/vundle ]; then
			echo "Installing Vundle for VIM configuration"
			mkdir -p ~/.vim
			git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
		fi
		vim -u $HOME/.vimrc.bundles +BundleInstall +qa
	fi
else
	distro=$(lsb_release -i | cut -f2-)

	if [ -f /etc/redhat-release ]; then
		echo "Fedora / RHEL detected"
	fi

	if [ "$distro" = "Ubuntu" ]; then
		echo "Ubuntu detected"
	fi
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:jsmestad/dfiles.git"

