#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  echo "macOS detected"

  if [ ! command -v brew >/dev/null 2>&1]; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


    echo "Configure Yubikey dependencies"
    brew install gnupg yubikey-personalization hopenpgp-tools pinentry-mac
    brew install direnv
  fi

  echo "Install iTerm2 color scheme"
  echo "Run `wget https://raw.githubusercontent.com/martinlindhe/base16-iterm2/master/itermcolors/base16-monokai-256.itermcolors` and install it"

else
  distro=$(lsb_release -i | cut -f2-)
  if [ -f /etc/redhat-release ]; then
    echo "Fedora / RHEL detected"
    sudo yum install direnv
  fi

  if [ "$distro" = "Ubuntu" ]; then
    echo "Ubuntu detected"
    sudo apt install -y pinentry-gnome3 pinentry-curses direnv dconf-cli

    echo "Configure Yubikey dependencies"
    sudo apt install -y gnupg2 gnupg-agent pinentry-curses scdaemon pcscd yubikey-personalization libusb-1.0-0-dev
  fi


  if [ ! -d ~/.config/base16-gnome-terminal ]; then
    echo "Fetching base16 themes for gnome terminal"
    git clone https://github.com/aaron-williamson/base16-gnome-terminal.git ~/.config/base16-gnome-terminal

    echo "Installing Monokai theme `~/.config/base16-gnome-terminal/color-scripts/base16-monokai.sh`"
    source ~/.config/base16-gnome-terminal/color-scripts/base16-monokai.sh
  fi

  # Download GPG key from Public Server
  gpg --list-keys 0xDB57958A3B574D5C > /dev/null 2>&1
  status=$?
  if [ $status -ne 0 ]; then
    echo "GPG key missing. Importing from Public Server."
    gpg --recv 0xDB57958A3B574D5C
    echo "GPG imported. You must manually trust it."
    echo "Run 'gpg --edit-key 0xDB57958A3B574D5C' and give it ultimate trust."

    # Run GPG with SSH
    GPG_TTY="$(tty)"
    SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    gpgconf --launch gpg-agent

    ssh-add -L | grep "cardno:000607123960" > ~/.ssh/id_rsa_yubikey.pub
  fi

fi

if [ command -v vim > /dev/null 2>&1]; then
  if [ ! -e $HOME/.vim/bundle/vundle ]; then
    echo "Installing Vundle for VIM configuration"
    mkdir -p ~/.vim
    git clone https://github.com/gmarik/vundle.git $HOME/.vim/bundle/vundle
  fi
  vim -u $HOME/.vimrc.bundles +BundleInstall +qa
fi

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:jsmestad/dfiles.git"

